### ISSUE TITLE
[BUG/ISSUE] Chat system cannot be trained

### ISSUE THREAD

**Issue by windowsboy111** [windowsboy111/merlin-py#23]
**Describe the bug**
This problem does not exist on my machine but it happens on repl.it. apparently the bot hosted on repl.it fails to train the chat system. 

**To Reproduce**
1. start the bot
2. in a chat channel (aka merlin-chat), run `merlin::train`
3. go to bot stdout
4. See error:
```
Process Merlin chat train:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/merlin-py/ext/chat/chat.py", line 48, in train
    trainer.train(conversation)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
```

**Expected behavior**
It should train itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/48051237/89120543-c709d400-d4e9-11ea-97e7-b9fb285fc224.png)

**Desktop (please complete the following information):**
- discord.py 1.3.4
- Linux (repl.it)
- python 3.8
- package manager: poetry
- chatterbot 0.8.7
- chatterbot-corpus 1.1.4

**Additional context**
The problem seems to be caused depending on the package manager of python. in repl.it, the package manager Poetry has a bug which will install / remove packages not intendedly.

**Comment by windowsboy111** [comment]
After a bit of diagnosing, the issue seems to be related to [the syntax changes and package version of chatterbot module](https://github.com/gunthercox/ChatterBot/issues/1426#issuecomment-425642143).
